language: java
jdk:
  - openjdk11

branch:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

env:
  - DOCKER_COMPOSE_VERSION=1.25.0

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

script:
  - ./gradlew clean build -x test
  - docker-compose build

before_deploy:
  - mkdir -p app_bundle
  - docker save -o wheretruck_app.tar wheretruck_app
  - docker save -o wheretruck_nginx.tar wheretruck_nginx
  - cp docker-compose.yml appspec.yml wheretruck_app.tar wheretruck_nginx.tar app_bundle/
  - cp scripts/deploy.sh app_bundle/
  - cd app_bundle && zip -r app_bundle *
  - cd ../ && mkdir -p deploy
  - mv app_bundle/app_bundle.zip deploy/app_bundle.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: wheretruck-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true
  
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: wheretruck-build
    key: app_bundle.zip
    bundle_type: zip
    application: wheretruck
    deployment_group: wheretruck-group
    region: ap-northeast-2
    wait-until-deployed: true

notifications:
  email:
    recipients:
      - "yaincoding@gmail.com"