version: "3.7"

services:
  app:
    build:
      context: .
    expose:
      - 8080
    volumes: 
      - type: bind
        source: $HOME/app-config
        target: /app-config

  nginx:
    build:
      context: ./nginx
    ports: 
      - "80:80"
      - "8080:8080"
    depends_on: 
      - app