spring:
  profiles:
    include:
    - aws
    - elasticsearch
    - jwt

elasticsearch:
  index:
    region:
      name: region
    truck:
      name: truck
    user:
      name: user
    favorite:
      name: favorite

cloud:
  aws:
    region:
      auto: false
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      instance-profile: false
    s3:
      bucket: 
        truck_image: wheretruck-truck-image
        food_image: wheretruck-food-image

oauth2:
  provider:
    kakao:
      user_info_url: https://kapi.kakao.com/v2/user/me
      auth: Bearer
      logout_url: https://kapi.kakao.com/v1.user/logout
    apple:
      public_key_url: https://appleid.apple.com/auth/keys
      