es:
  host: ec2-13-209-181-246.ap-northeast-2.compute.amazonaws.com
  port: 9200
  index:
    region:
      name: region
    truck:
      name: truck
    food:
      name: food
    rating:
      name: rating