spring:
  application:
    name: wheretruck
  profiles:
    include:
    - elasticsearch
    - aws

elasticsearch:
  host: ec2-13-209-181-246.ap-northeast-2.compute.amazonaws.com
  port: 9200
  index:
    region:
      name: region
    truck:
      name: truck
    user:
      name: user

cloud:
  aws:
    region:
      auto: false
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      instance-profile: false
    s3:
      bucket: 
        food_image: wheretruck-food-image

jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-ms: 86400000

oauth2:
  provider:
    kakao:
      user_info_url: https://kapi.kakao.com/v2/user/me
      auth: Bearer
      logout_url: https://kapi.kakao.com/v1.user/logout
    apple:
      public_key_url: https://appleid.apple.com/auth/keys
      